# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

target 'WCTMoveLearnDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # 网络请求
  pod 'Alamofire'
  # Json解析
  pod 'SwiftyJSON'
  #
  pod 'HandyJSON'
  # 图片显示框架
  pod 'Kingfisher'
  
  # XIB 功能框架
  pod 'IBAnimatable'
  
  # 切换t主题框架
  pod 'SwiftTheme'
  
  #
  pod 'RxSwift'
  pod 'RxCocoa'
end
